## an okayish way of detecting platforms
if(WIN32)
  set(WINDOWS TRUE)
  set(PLATFORM Windows)
  message("WINDOWS DETECTED")
elseif(APPLE)
  set(OSX TRUE)
  set(PLATFORM OSX)
  message("OSX DETECTED")
elseif(UNIX AND NOT APPLE)
  set(LINUX TRUE)
  set(PLATFORM Linux)
  message("LINUX DETECTED")
endif()

## are we running a windows compiler
if(MSVC OR MSYS OR MINGW)
  message("Compiling on Windows")
  set(WIN_COMPILER TRUE)
endif()
